[project]
ref = "afovfoaraolalebvookx"
name = "droplog"

[api]
enabled = true
port = 54321

[db.migrations]
directory = "./supabase"

[functions]
enabled = true
include = ["send-eta", "delivery-notify"]

[functions.send-eta]
verify_jwt = false

[functions.delivery-notify]
verify_jwt = false
